name: test-conda
channels:
  - conda-forge
  - defaults
dependencies:
  - cffi>=1.3.0
  - codecov
  - libsecp256k1
  - pkgconfig
  - pytest
  - pytest-cov
  - pytest-benchmark
  - setuptools >61
  - tox
  - tox-conda
