name: test-conda
channels:
  - conda-forge
  - defaults
dependencies:
  - tox
  - codecov
  - pip
  - libsecp256k1
  - pkgconfig
  - setuptools >61
  - pytest
  - pytest-cov
  - pytest-benchmark
  - cffi>=1.3.0
